# IRCoT demo

# MCP Server
servers:
  benchmark: servers/benchmark
  generation: servers/generation
  retriever: servers/retriever
  prompt: servers/prompt
  evaluation: servers/evaluation
  router: servers/router
  custom: servers/custom

# MCP Client Pipeline
pipeline:
- benchmark.get_data
# 前n-1次检索，需要提取CoT的第一句话
- loop:
    times: 2
    steps:
    # 检索Q->D
    - retriever.retriever_deploy_search
    # T_i = Reason(Q + D + T_i-1)
    - prompt.ircot_next_prompt
    - generation.generate
    - branch:
        router:
        # 判断是否包含so the answer is
        - router.ircot_check_end
        branches:
          incomplete:
          # 提取第一句话作为CoT
          - custom.ircot_get_first_sent
          complete: []
# 第n次检索，不提取第一句话
# T_3 = Reason(Q + D + T_2)
- retriever.retriever_deploy_search
- prompt.ircot_next_prompt
- generation.generate
- custom.ircot_extract_ans
- evaluation.evaluate
