# Search-R1 Demo

# MCP Server
servers:
  benchmark: servers/benchmark
  generation: servers/generation
  retriever: servers/retriever
  prompt: servers/prompt
  evaluation: servers/evaluation
  router: servers/router
  custom: servers/custom

# MCP Client Pipeline
pipeline:
# 加载数据集
- benchmark.get_data
# 初始prompt
- prompt.qa_boxed
# 首次生成答案
- generation.generate
- loop:
    times: 5
    steps:
    # 触发器检查，判断问题是否解决
    - branch:
        router:
        - router.search_r1_check
        branches:
          # 如果问题没有解决，继续
          incomplete:
          # 提取查询query
          - custom.search_r1_query_extract
          # 检索相关文档
          - retriever.retriever_deploy_search:
              input:
                query_list: extract_query_list
          # 将文档与历史prompt拼接
          - prompt.search_r1_gen
          # 生成答案
          - generation.generate
          # 如果问题被解决，结束
          complete: []
# 评估结果
- evaluation.evaluate:
    input:
      pred_ls: ans_ls
