# Vanilla LLM demo for multiple choice dataset

# MCP Server
servers:
  benchmark: servers/benchmark
  prompt: servers/prompt
  generation: servers/generation
  evaluation: servers/evaluation
  custom: servers/custom

# MCP Client Pipeline
pipeline:
- benchmark.get_data
- prompt.qa_boxed_multiple_choice
- generation.generate
- custom.output_extract_from_boxed
- evaluation.evaluate
